export const arr = [
  {
    id: 1,
    imgSrc: "../public/busket.png",
    name: "Эмаль Condor ПФ-115",
    count: 500,
    isCount: 1000,
    spanCount: 2,
    num: 2,
  },
  {
    id: 2,
    imgSrc: "../public/busket.png",
    name: "Эмаль Condor ПФ-115",
    count: 150,
    isCount: 1000,
    spanCount: 2,
    num: 1,
  },
  {
    id: 3,
    imgSrc: "../public/busket.png",
    name: "Эмаль Condor ПФ-115",
    count: 300,
    isCount: 1000,
    spanCount: 2,
    num: 2,
  },
  {
    id: 4,
    imgSrc: "../public/busket.png",
    name: "Эмаль Condor ПФ-115",
    count: 1500,
    isCount: 1000,
    spanCount: 2,
    num: 1,
  },
  {
    id: 5,
    imgSrc: "../public/busket.png",
    name: "Эмаль Condor ПФ-115",
    count: 100,
    isCount: 100,
    spanCount: 2,
    num: 3,
  },
  {
    id: 6,
    imgSrc: "../public/busket.png",
    name: "Эмаль Condor ПФ-115",
    count: 500,
    isCount: 500,
    spanCount: 2,
    num: 2,
  },
];
